#!/usr/bin/env bash
set -euxo pipefail

function check_continue {
    read -rp "$1 (y/N) " yn
    if [ "$yn" != "y" ]; then
        exit 1
    fi
}

if test -f "hosts/$(hostname)/install"; then
    echo "Running hostname-specific install"

    . "hosts/$(hostname)/install"
fi
