#!/usr/bin/env bash
set -euo pipefail

function check_continue {
    read -p "$1 (y/N) " yn
    if [ "$yn" != "y" ]; then
        exit 1
    fi
}

check_continue "Replace .git/hooks/pre-commit?"
ln -sf ../../nixfmt-check .git/hooks/pre-commit

if test -f "`hostname`/configuration.nix"; then
    check_continue "Replace /etc/nixos/configuration.nix?"

    sudo ln -sf $HOME/dotfiles/`hostname`/configuration.nix /etc/nixos/configuration.nix

    check_continue "Switch to NixOs unstable?"
    sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    sudo nixos-rebuild switch --upgrade
else
    echo "Not on NixOs!"
    echo "You may need to install nscd"
    echo "See: https://github.com/NixOS/nixpkgs/issues/12335#issuecomment-212325290"
fi

if test -f "`hostname`/home.nix"; then
    check_continue "Replace $HOME/.config/nixpkgs/home.nix?"

    mkdir -p $HOME/.config/nixpkgs
    ln -sf $HOME/dotfiles/`hostname`/home.nix $HOME/.config/nixpkgs/home.nix

    nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
    nix-channel --update

    echo "Installing. You may need to log out first on NixOs, or add a thing elsewhere."
    echo "See https://github.com/rycee/home-manager#installation"

    # For non-NixOs
    export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}

    nix-shell '<home-manager>' -A install
fi

