#!/usr/bin/env bash

set -euo pipefail

echo "Make sure to create the following files in ~/secrets:"
echo "gandi_api_key"
echo "pia_username"
echo "pia_password"
echo "wireguard.key"
echo ""
echo "Thank you!"
