#!/usr/bin/env bash

set -euo pipefail

echo "Make sure to create the following files in dotfiles/hosts/box:"
echo "API_KEY - for Gandi for ddns"
echo "PIA_USERNAME"
echo "PIA_PASSWORD"
echo ""
echo "Thank you!"
