promptToReturnFromSubprocess: false
os:
  editPreset: "helix (hx)"
gui:
  theme:
    selectedLineBgColor:
      - "#444444"
    inactiveViewSelectedLineBgColor:
      - "#262626"
git:
  diffRenderers:
    - command: delta --dark --paging=never
    - command: difft --color=always
      type: extDiff
