#!/usr/bin/env bash

set -euxo pipefail

nix-channel --add https://github.com/guibou/nixGL/archive/main.tar.gz nixgl
nix-channel --update
nix-env -iA nixgl.auto.nixGLDefault

sudo apt install slock xss-lock