#!/usr/bin/env bash

set -euxo pipefail

nix-channel --add https://github.com/guibou/nixGL/archive/main.tar.gz nixgl
nix-channel --update
nix-env -iA nixgl.auto.nixGLDefault

sudo apt-get update
# screen lockers -- still relevant?
sudo apt-get install slock xss-lock

# for display-switch
sudo apt-get install libxi-dev xorg-dev
sudo groupadd i2c
echo 'KERNEL=="i2c-[0-9]*", GROUP="i2c"' | sudo tee -a /etc/udev/rules.d/10-local_i2c_group.rules
sudo udevadm control --reload-rules && sudo udevadm trigger
sudo usermod -aG i2c "$(whoami)"
